### ISSUE TITLE
A problem about the RS-YOLACT

### ISSUE THREAD

**Issue by xiehousen** [kemaloksuz/RankSortLoss#10]
I use your code and the model provided to infer RS-yolact. The inference effect is shown in the figure below. What is the reason?
![000000003553](https://user-images.githubusercontent.com/37787619/133035011-76db9948-f6e6-49ec-a95a-4e582962af8b.jpg)

YOLACT is OK.

**Comment by cancam** [comment]
@xiehousen Thank you for your interest in our work. In order to reproduce the error, I listed some comments below:

First I validated the result we reported on the GitHub project page for YOLACT and it seems correct. To do this I used the config file in this [link](https://github.com/kemaloksuz/RankSortLoss/blob/main/configs/ranksort_loss/ranksort_yolact_r50_55e_coco.py). Could you please validate whether you used the same config file or not? 

In addition to this, I am wondering whether the image you provided is from the COCO dataset or not? If yes, could you please provide the image id for me to reproduce the same erroneous result?

Best,
Baris.

**Comment by xiehousen** [comment]
Thanks for your reply.
The config file that I used to inference is the `configs/ranksort_loss/ranksort_yolact_r50_55e_coco.py`.  The model is the model you provided. 
I use the test code to verify the indicators of rs-yoact in the coco data set, and the results are the same as those shown on GitHub. However, when I use demo code for inference, the above problem occurs, and I haven't changed the code.
I use the coco dataset, and most images have this problem, not a few images have this problem. the image aforementioned is 000000003553.jpg.

Thanks for your reply.

**Comment by kemaloksuz** [comment]
Hi! 

With @cancam, we have completed the analysis why the result you shared is noisy. Below are the reason and how to get a better visualization:

- With RS Loss, we had previously observed that the confidence scores of the detections are larger than standard loss values. For example, even with long tailed LVIS dataset, we set the confidence score threshold to 0.60. Please compare Mask R-CNN and RS- Mask R-CNN below:
![image](https://user-images.githubusercontent.com/22542225/133656266-0da787e3-a15d-4093-acc5-0d2133770eee.png)

- Upon your problem, we have conducted a similar analysis on RS-YOLACT. Unlike the standard loss with 0.05 confidence score, we observed that 0.65 confidence score threshold still ensures the reported AP, that is 29.9 for mask prediction for RS-YOLACT.
- Also, note that when you want to visualize the detections, the general tendency is to choose a larger threshold (such as 0.25 for the standard YOLACT) in order to suppress the noisy detections. This is because, these noisy detections (such as the ones between 0.05-0.25) contribute to AP value, but not to practical usage. We discussed this drawback of AP in our previous papers on LRP Error (from ECCV 18 and its extension). If you look for further information on the reason, please check Fig. 7 in  https://arxiv.org/abs/2011.10772 stating "different from AP, AUC of PR curve, oLRP is not affected by low-precision detections in the tail of the PR curves"
- As a result, we searched a threshold that best visualize the results for RS-YOLACT and we observed that 0.80 seems to be a good visualization threshold. Below is the output of RS-YOLACT with 0.80, which seems a good detection output.
![image](https://user-images.githubusercontent.com/22542225/133657647-eddfb86b-2160-40e3-8684-c244b9f886a3.png)

Last comment: I think setting the threshold of classifiers is a challenging task. To do so, instead of tuning it like we did here, we proposed using LRP-Optimal Threshold (https://arxiv.org/abs/2011.10772), which assigns a class-specific optimal threshold instead of using a general threshold for the entire detector. Hence, if you look for better practical/visualization performance, I recommend using LRP-Optimal Threshold.

**Comment by xiehousen** [comment]
Thank you very much for your detailed reply. It is true that good results can be obtained by changing the threshold, but as you said, it is difficult to set this threshold. 
Later, I will read the LPR-Optimal paper, and try to apply it in the work.
